/**
 * Build identifier for this bundle.
 *
 * The values are substituted by Vite's `define` at build time — see
 * `buildVersion()` in vite.config.ts. `appVersion` used to be the hard-coded
 * string "1.0.0" in both apps, so every session looked like it came from the
 * same build; several behaviour-changing fixes can land in a day, and without a
 * stamp the sessions from before and after are indistinguishable in the
 * database.
 *
 * Declared locally rather than globally so the substitution is visible at the
 * one place it happens. The native app has the same module, generated by
 * `scripts/stamp-build.mjs`.
 */
declare const __APP_VERSION__: string;
declare const __BUILT_AT__: string;

// Vite substitutes these in both `dev` and `build`. Only the test runner has no
// `define`, so the fallback marks a bundle that was never stamped — which is a
// value worth seeing in the database rather than a crash.
export const APP_VERSION: string =
    typeof __APP_VERSION__ === "string" ? __APP_VERSION__ : "unstamped";
export const BUILT_AT: string =
    typeof __BUILT_AT__ === "string" ? __BUILT_AT__ : "unstamped";
